-- MySQL Script generated by MySQL Workbench
-- Do 05 Mär 2020 08:54:08 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema feedback
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema feedback
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `feedback` ;
USE `feedback` ;

-- -----------------------------------------------------
-- Table `feedback`.`mops.Fragebogen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `feedback`.`mops.Fragebogen` (
  `Formular_ID` BIGINT NOT NULL AUTO_INCREMENT,
  `Erstellungsdatum` DATETIME GENERATED ALWAYS AS (),
  `Ersteller` TEXT NOT NULL,
  `Formularname` TEXT NOT NULL,
  `Deadline` DATETIME NOT NULL,
  PRIMARY KEY (`Formular_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `feedback`.`mops.Frage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `feedback`.`mops.Frage` (
  `Frage_ID` BIGINT NOT NULL AUTO_INCREMENT,
  `Fragetext` TEXT NOT NULL,
  `Fragetyp` TEXT NOT NULL,
  `Fragerange` TEXT NOT NULL,
  `Formular_ID` BIGINT NULL,
  PRIMARY KEY (`Frage_ID`),
  INDEX `Formular_ID_idx` (`Formular_ID` ASC) VISIBLE,
  CONSTRAINT `fk_formularID`
    FOREIGN KEY (`Formular_ID`)
    REFERENCES `feedback`.`mops.Fragebogen` (`Formular_ID`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `feedback`.`Antwort`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `feedback`.`Antwort` (
  `Antwort_ID` BIGINT NOT NULL,
  `Antworttext` TEXT NOT NULL,
  `Frage_ID` BIGINT NULL,
  PRIMARY KEY (`Antwort_ID`),
  INDEX `fk_frageID_idx` (`Frage_ID` ASC) VISIBLE,
  CONSTRAINT `fk_frageID`
    FOREIGN KEY (`Frage_ID`)
    REFERENCES `feedback`.`mops.Frage` (`Frage_ID`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `feedback`.`Template`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `feedback`.`Template` (
  `Template_ID` BIGINT NOT NULL AUTO_INCREMENT,
  `Formular_ID` BIGINT NULL,
  `Templatename` TEXT NOT NULL,
  PRIMARY KEY (`Template_ID`),
  INDEX `Formular_ID_idx` (`Formular_ID` ASC) VISIBLE,
  CONSTRAINT `fk_formularID`
    FOREIGN KEY (`Formular_ID`)
    REFERENCES `feedback`.`mops.Fragebogen` (`Formular_ID`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
